using Microsoft.OpenApi;
using OpenIddict.Client;
using Shared.Middleware;

namespace EstateReportingAPI.Bootstrapper{
    using System.Diagnostics.CodeAnalysis;
    using System.Net.Security;
    using System.Reflection;
    using Common;
    using Lamar;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.Extensions.Diagnostics.HealthChecks;
    using Microsoft.IdentityModel.Tokens;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;
    using Shared.General;
    using Swashbuckle.AspNetCore.Filters;

    [ExcludeFromCodeCoverage]
    public class MiddlewareRegistry : ServiceRegistry{
        public MiddlewareRegistry()
        {
            this.ConfigureHealthChecks();
            this.ConfigureSwagger();
            this.ConfigureAuthentication();
            this.ConfigureControllers();
            this.ConfigureMiddlewareLogging();
            this.ConfigureHttpJsonOptions(options =>
            {
                options.SerializerOptions.PropertyNamingPolicy = new SnakeCaseNamingPolicy();
                options.SerializerOptions.PropertyNameCaseInsensitive = true; // optional, but safer
            });
        }

        private void ConfigureHealthChecks(){
            var connectionStringSection = Startup.Configuration.GetSection("ConnectionStrings");
            if (connectionStringSection.Exists() == false)
            {
                this.AddHealthChecks();
            }
            else
            {
                this.AddHealthChecks().AddSqlServer(
                    connectionString: ConfigurationReader.GetConnectionString("HealthCheck"),
                    healthQuery: "SELECT 1;",
                    name: "Read Model Server",
                    failureStatus: HealthStatus.Degraded,
                    tags: new[] { "db", "sql", "sqlserver" });
            }
        }

        private void ConfigureSwagger(){
            this.AddSwaggerGen(c => {
                                   c.SwaggerDoc("v1",
                                                new OpenApiInfo{
                                                                   Title = "Estate Reporting API",
                                                                   Version = "1.0",
                                                                   Description = "A REST Api to manage all aspects of reporting for an estate (merchants, operators and contracts).",
                                                                   Contact = new OpenApiContact{
                                                                                                   Name = "Stuart Ferguson",
                                                                                                   Email = "golfhandicapping@btinternet.com"
                                                                                               }
                                                               });
                                   // add a custom operation filter which sets default values
                                   c.OperationFilter<SwaggerDefaultValues>();
                                   c.ExampleFilters();

                                   //Locate the XML files being generated by ASP.NET...
                                   var directory = new DirectoryInfo(AppContext.BaseDirectory);
                                   var xmlFiles = directory.GetFiles("*.xml");

                                   //... and tell Swagger to use those XML comments.
                                   foreach (FileInfo fileInfo in xmlFiles){
                                       c.IncludeXmlComments(fileInfo.FullName);
                                   }
                               });

            this.AddSwaggerExamplesFromAssemblyOf<SwaggerJsonConverter>();
        }

        private void ConfigureAuthentication(){
            String? inTestMode = Environment.GetEnvironmentVariable("InTestMode");
            if (String.Compare(inTestMode, Boolean.TrueString, StringComparison.InvariantCultureIgnoreCase) != 0){
                this.AddOpenIddict()
                    // Register the OpenIddict client components.
                    .AddClient(options => {
                        // Allow grant_type=client_credentials to be negotiated.
                        options.AllowClientCredentialsFlow();

                        // Disable token storage, which is not necessary for non-interactive flows like
                        // grant_type=password, grant_type=client_credentials or grant_type=refresh_token.
                        options.DisableTokenStorage();

                        // Register the System.Net.Http integration and use the identity of the current
                        // assembly as a more specific user agent, which can be useful when dealing with
                        // providers that use the user agent as a way to throttle requests (e.g Reddit).
                        options.UseSystemNetHttp().SetProductInformation(typeof(Program).Assembly);

                        // Add a client registration matching the client application definition in the server project.
                        options.AddRegistration(new OpenIddictClientRegistration { Issuer = new Uri(ConfigurationReader.GetValue("SecurityConfiguration", "Authority"), UriKind.Absolute), ClientId = ConfigurationReader.GetValue("SecurityConfiguration", "ApiName") });
                    });
            }
        }

        private void ConfigureControllers(){
            this.AddControllers().AddNewtonsoftJson(options => {
                                                        options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                                                        options.SerializerSettings.TypeNameHandling = TypeNameHandling.None;
                                                        options.SerializerSettings.Formatting = Formatting.Indented;
                                                        options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Unspecified;
                                                        options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                                                    });

            Assembly assembly = this.GetType().GetTypeInfo().Assembly;
            this.AddMvcCore().AddApplicationPart(assembly).AddControllersAsServices();
        }

        private void ConfigureMiddlewareLogging(){
            bool logRequests = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogRequests", true);
            bool logResponses = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogResponses", true);
            LogLevel middlewareLogLevel = ConfigurationReader.GetValueOrDefault<LogLevel>("MiddlewareLogging", "MiddlewareLogLevel", LogLevel.Warning);

            RequestResponseMiddlewareLoggingConfig config =
                new RequestResponseMiddlewareLoggingConfig(middlewareLogLevel, logRequests, logResponses);

            this.AddSingleton(config);
        }

        private HttpClientHandler ApiEndpointHttpHandler(IServiceProvider serviceProvider){
            return new HttpClientHandler{
                                            ServerCertificateCustomValidationCallback = (message,
                                                                                         cert,
                                                                                         chain,
                                                                                         errors) => {
                                                                                            return true;
                                                                                        }
                                        };
        }
    }
}