using Microsoft.OpenApi;
using Shared.Middleware;

namespace EstateReportingAPI.Bootstrapper{
    using Common;
    using Lamar;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.Extensions.Diagnostics.HealthChecks;
    using Microsoft.IdentityModel.Tokens;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;
    using OpenIddict.Validation.AspNetCore;
    using Shared.General;
    using Swashbuckle.AspNetCore.Filters;
    using System.Diagnostics.CodeAnalysis;
    using System.Net.Security;
    using System.Reflection;

    [ExcludeFromCodeCoverage]
    public class MiddlewareRegistry : ServiceRegistry{
        public MiddlewareRegistry()
        {
            this.ConfigureHealthChecks();
            this.ConfigureSwagger();
            this.ConfigureAuthentication();
            this.ConfigureControllers();
            this.ConfigureMiddlewareLogging();
            this.ConfigureHttpJsonOptions(options =>
            {
                options.SerializerOptions.PropertyNamingPolicy = new SnakeCaseNamingPolicy();
                options.SerializerOptions.PropertyNameCaseInsensitive = true; // optional, but safer
            });
        }

        private void ConfigureHealthChecks(){
            var connectionStringSection = Startup.Configuration.GetSection("ConnectionStrings");
            if (connectionStringSection.Exists() == false)
            {
                this.AddHealthChecks();
            }
            else
            {
                this.AddHealthChecks().AddSqlServer(
                    connectionString: ConfigurationReader.GetConnectionString("HealthCheck"),
                    healthQuery: "SELECT 1;",
                    name: "Read Model Server",
                    failureStatus: HealthStatus.Degraded,
                    tags: new[] { "db", "sql", "sqlserver" });
            }
        }

        private void ConfigureSwagger(){
            this.AddSwaggerGen(c => {
                                   c.SwaggerDoc("v1",
                                                new OpenApiInfo{
                                                                   Title = "Estate Reporting API",
                                                                   Version = "1.0",
                                                                   Description = "A REST Api to manage all aspects of reporting for an estate (merchants, operators and contracts).",
                                                                   Contact = new OpenApiContact{
                                                                                                   Name = "Stuart Ferguson",
                                                                                                   Email = "golfhandicapping@btinternet.com"
                                                                                               }
                                                               });
                                   // add a custom operation filter which sets default values
                                   c.OperationFilter<SwaggerDefaultValues>();
                                   c.ExampleFilters();

                                   //Locate the XML files being generated by ASP.NET...
                                   var directory = new DirectoryInfo(AppContext.BaseDirectory);
                                   var xmlFiles = directory.GetFiles("*.xml");

                                   //... and tell Swagger to use those XML comments.
                                   foreach (FileInfo fileInfo in xmlFiles){
                                       c.IncludeXmlComments(fileInfo.FullName);
                                   }
                               });

            this.AddSwaggerExamplesFromAssemblyOf<SwaggerJsonConverter>();
        }

        private void ConfigureAuthentication(){
            String? inTestMode = Environment.GetEnvironmentVariable("InTestMode");
            if (String.Compare(inTestMode, Boolean.TrueString, StringComparison.InvariantCultureIgnoreCase) != 0){
                this.AddAuthentication(options =>
                {
                    options.DefaultScheme = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
                });

                this.AddOpenIddict()
                    .AddValidation(options =>
                    {
                        // Same as your Authority
                        options.SetIssuer(new Uri(ConfigurationReader.GetValue("SecurityConfiguration", "Authority")));

                        // Enables discovery and HTTP backchannel support
                        options.UseSystemNetHttp()
                            .ConfigureHttpClientHandler(handler =>
                            {
                                // DEV ONLY: bypass all certificate errors
                                handler.ServerCertificateCustomValidationCallback =
                                    HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
                            });

                        // Register the ASP.NET Core integration
                        options.UseAspNetCore();

                        // Optionally set expected audience(s):
                        options.AddAudiences(ConfigurationReader.GetValue("SecurityConfiguration", "ApiName"));

                    });

                this.AddAuthorization();
            }
        }

        private void ConfigureControllers(){
            this.AddControllers().AddNewtonsoftJson(options => {
                                                        options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                                                        options.SerializerSettings.TypeNameHandling = TypeNameHandling.None;
                                                        options.SerializerSettings.Formatting = Formatting.Indented;
                                                        options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Unspecified;
                                                        options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                                                    });

            Assembly assembly = this.GetType().GetTypeInfo().Assembly;
            this.AddMvcCore().AddApplicationPart(assembly).AddControllersAsServices();
        }

        private void ConfigureMiddlewareLogging(){
            bool logRequests = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogRequests", true);
            bool logResponses = ConfigurationReader.GetValueOrDefault<Boolean>("MiddlewareLogging", "LogResponses", true);
            LogLevel middlewareLogLevel = ConfigurationReader.GetValueOrDefault<LogLevel>("MiddlewareLogging", "MiddlewareLogLevel", LogLevel.Warning);

            RequestResponseMiddlewareLoggingConfig config =
                new RequestResponseMiddlewareLoggingConfig(middlewareLogLevel, logRequests, logResponses);

            this.AddSingleton(config);
        }

        private HttpClientHandler ApiEndpointHttpHandler(IServiceProvider serviceProvider){
            return new HttpClientHandler{
                                            ServerCertificateCustomValidationCallback = (message,
                                                                                         cert,
                                                                                         chain,
                                                                                         errors) => {
                                                                                            return true;
                                                                                        }
                                        };
        }
    }
}