name: Build and Test Pull Requests

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: "Build and Test Pull Requests"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
        
    - name: Restore Nuget Packages
      run: dotnet restore EstateReportingAPI.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build EstateReportingAPI.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "EstateReportingAPI.Tests\EstateReportingAPI.Tests.csproj"
        
    - name: Run Integration Tests
      run: |
        dotnet test "EstateReportingAPI.IntegrationTests\EstateReportingAPI.IntegrationTests.csproj"

    - uses: actions/upload-artifact@v4.4.0
      if: ${{ failure() }}
      with:
        name: tracelogs
        path: /home/txnproc/trace/   
